apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr
        env:
        - name: PUID
          value: "1057"  
        - name: PGID
          value: "1056"  
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        ports:
        - name: http
          containerPort: 7878
      volumes:
        - name: data
          nfs:
            server: your-nfs-server
            path: /your/path/to/data
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
