apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
- ../../../../../base/networkpolicies

replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: NetworkPolicy
        fieldPaths:
          - spec.ingress[0].from[0].namespaceSelector.matchLabels.kubernetes.io/metadata.name
