---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/test-nginx

patches:
  - path: patch.yaml

namespace: test-argocd-kustomize

labels:
  - pairs:
      environment: prod
      cluster: k8s-01
