apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-lb-to-immich
spec:
  endpointSelector:
    matchExpressions:
      - key: app.kubernetes.io/part-of
        operator: In
        values: [immich]
  ingress:
  - fromCIDR:
    - 0.0.0.0/0 
    toPorts:
    - ports:
      - port: "2283"
        protocol: TCP
  egress:
    - toEndpoints:
        - {}
