apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: synology.home.adamatyi.com
    path: /volume1/immich        # <-- your real export path
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  storageClassName: ""
  claimRef:
    namespace: immich
    name: immich-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 500Gi
