controllers:
  main:
    containers:
      main:
        image:
          tag: v3.0.0
        env:
          DB_HOSTNAME: immich-pg-rw
          DB_DATABASE_NAME: immich
          DB_USERNAME:
            valueFrom:
              secretKeyRef: { name: immich-pg-app, key: username }
          DB_PASSWORD:
            valueFrom:
              secretKeyRef: { name: immich-pg-app, key: password }

immich:
  persistence:
    library:
      existingClaim: immich-library

valkey:
  enabled: true
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      size: 1Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn

machine-learning:
  enabled: true
  controllers:
    main:
      strategy: Recreate
  persistence:
    cache:
      enabled: true
      type: persistentVolumeClaim
      size: 10Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn

server:
  enabled: true
  controllers:
    main:
      strategy: Recreate
  ingress:
    main:
      enabled: false
