---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  template:
    spec:
      volumes:
        - name: data
          nfs:
            server: synology.home.adamatyi.com
            path: /volume1/media/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config
spec:
  nfs:
    path: /volume1/k8s/prod/k8s-01
    server: synology.home.adamatyi.com
