---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  template:
    spec:
      volumes:
        - name: data
          nfs:
            server: synology.home.adamatyi.com
            path: /volume1/media/
