apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-lb-to-seerr
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: seerr-chart
      app.kubernetes.io/instance: seerr
  ingress:
  - fromCIDR:
    - 10.10.30.110/32 
    toPorts:
    - ports:
      - port: "5055"
        protocol: TCP
