---
# Source: seerr-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seerr-seerr-chart
  labels:
    helm.sh/chart: seerr-chart-3.3.0
    app.kubernetes.io/name: seerr-chart
    app.kubernetes.io/instance: seerr
    app.kubernetes.io/version: "v3.1.0"
    app.kubernetes.io/part-of: seerr-chart
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
