---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/prowlarr

namespace: media

patches:
  - path: patch.yaml

labels:
  - pairs:
      environment: prod
      cluster: k8s-01
