---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  template:
    spec:
      volumes:
        - name: media
          nfs:
            server: synology.home.adamatyi.com
            path: /volume1/media
